---
title: Examen diagnóstico - Solución
subtitle: Análisis Estadístico Multivariado
author:  |
    | ITESO
    | Departamento de Matemáticas y Física  
format:
  pdf: 
    include-in-header: 
      text: |
            \usepackage{amsmath}
            \usepackage{amsfonts}
            \usepackage{amssymb}
            \usepackage{unicode-math,color}
            \usepackage{color}
            \setmathfont[Color=FF0000]{latinmodern-math.otf}
            \setmathfont[range=\mathit/{greek,Greek},Color=blue]{latinmodern-math.otf} % sets greek letters to blue
            \usepackage{enumitem}
    number-sections: true
    colorlinks: true
    number-depth: 0
fig-pos: 'H'
---


# Cálculo

1. Resolver las siguientes derivadas

\begin{enumerate}[label={(\alph*)}]
  \setlength{\itemsep}{0pt}
  \setlength{\parskip}{0pt}
  \setlength{\parsep}{0pt}
  \item  $$\frac{\text{d}}{\text{d}x}(x^2 + 2x + 1)$$
  R. $2x + 2$
  \item $$\frac{\text{d}}{\text{d}x}\left( \frac{1+x}{1-x} \right)$$
  R. $\frac{2}{(1-x)^2}$
  \item Sea la función de log-verosimilitud $l(\theta)=\log \theta^k + \log(1-\theta)^{n-k}$. Obtener $$\frac{\partial l(\theta)}{\partial \theta}$$
  R. $\frac{k}{\theta} - \frac{n-k}{1-\theta}$
\end{enumerate}

2. a) ¿Cuál es la interpretación geométrica de la primera derivada? R. **Pendiente de la recta tangente de la función evaluada en $c$**
b) ¿Qué valor tiene la primera derivada de una función cuando la función se encuentra en un máximo? R. $0$.

3. Si la función es convexa en el rango $[a, b]$, ¿obtenemos un mínimo o un máximo? R. **Mínimo**

4. Resolver las siguientes integrales

\begin{enumerate}[label={(\alph*)}]
  \setlength{\itemsep}{0pt}
  \setlength{\parskip}{0pt}
  \setlength{\parsep}{0pt}
  \item $$\int_0^1 \frac{\text{d}x}{\sqrt[3]{x}}$$
  R. $\frac{3}{2}$
  \item Para la función de densidad
  $$
      f_{xy}(x,y)=\frac{1}{2}x + \frac{3}{2}y,\quad \text{para } 0 \leq x\leq 1, 0 \leq y \leq 1
  $$
  Encontrar
  $$
      F(x,y)=\int_0^{x}\int_0^y\left( \frac{1}{2}u + \frac{3}{2}v\right)\text{d}v\text{d}u
  $$
  R. $\frac{x^2y}{4} + \frac{3xy^2}{4}$
\end{enumerate}

# Estadística y probabilidad

1. ¿Qué mide la correlación?
R. **Dependencia lineal entre dos variables. La relación puede ser ser positiva o negativa**
2. Menciona dos medidas de tendencia central.
R. **Media, mediana**
3. Menciona dos medidas de dispersión.
R. **Desviación estándar, rango intercuartílico**
4. ¿Qué es una variable aleatoria?
R. **Una función que asigna un valor numérico al resultado de un experimento aleatorio. Si $\omega$ es uno de esos resultados (por ejemplo, el resultado de lanzar una moneda), y $X$ la variable aleatoria, la función es $X(\omega)\in \mathbb{R}$**.
5. ¿Cuál es la diferencia entre funciones de densidad de probabilidad y funciones de masa de probabilidad?
R. **Las funciones de densidad son funciones que asignan un valor $f(x)\in [0, 1]$ a una variable aleatoria continua. Las funciones de masa asignan una probabilidad $p(x)\in [0, 1]$ al resultado de una variable aleatoria discreta.**
6. Respecto a la anterior pregunta, ¿con qué tipo de función (de masa o densidad) usarías cuál ecuación para obtener el valor esperado?

\begin{enumerate}
  \setlength{\itemsep}{0pt}
  \setlength{\parskip}{0pt}
  \setlength{\parsep}{0pt}
  \item ¿De masa o de densidad?
  $$
    \mathbf{E}[x] = \sum_{i=1}^n x_ip_i
  $$
  R. \textbf{De masa}
  \item ¿De masa o de densidad?
  $$
    \mathbf{E}[x] = \int xf(x)\text{d}x
  $$
  R. \textbf{De densidad}. Lo sabemos porque hay que integrar para obtener una densidad,
\end{enumerate}