---
title: Examen diagnóstico
subtitle: Análisis Estadístico Multivariado
author:  |
    | ITESO
    | Departamento de Matemáticas y Física  
format:
  pdf: 
    include-in-header: 
      text: |
        \usepackage{amsmath}
        \usepackage{amsfonts}
        \usepackage{amssymb}
        \usepackage{enumitem}
    number-sections: true
    colorlinks: true
    number-depth: 0
fig-pos: 'H'
---

# Cálculo

1. Resolver las siguientes derivadas

\begin{enumerate}[label={(\alph*)}]
  \setlength{\itemsep}{0pt}
  \setlength{\parskip}{0pt}
  \setlength{\parsep}{0pt}
  \item  $$\frac{\text{d}}{\text{d}x}(x^2 + 2x + 1)$$
  \item $$\frac{\text{d}}{\text{d}x}\left( \frac{1+x}{1-x} \right)$$
  \item Sea la función de log-verosimilitud $l(\theta)=\log \theta^k + \log(1-\theta)^{n-k}$. Obtener $$\frac{\partial l(\theta)}{\partial \theta}$$
\end{enumerate}

2. a) ¿Cuál es la interpretación geométrica de la primera derivada? b) ¿Qué valor tiene la primera derivada de una función cuando la función se encuentra en un máximo?

3. Si la función es convexa en el rango $[a, b]$, ¿obtenemos un mínimo o un máximo?

4. Resolver las siguientes integrales

\begin{enumerate}[label={(\alph*)}]
  \setlength{\itemsep}{0pt}
  \setlength{\parskip}{0pt}
  \setlength{\parsep}{0pt}
  \item $$\int_0^1 \frac{\text{d}x}{\sqrt[3]{x}}$$
  \item Para la función de densidad
  $$
      f_{xy}(x,y)=\frac{1}{2}x + \frac{3}{2}y,\quad \text{para } 0 \leq x\leq 1, 0 \leq y \leq 1
  $$
  Encontrar
  $$
      F(x,y)=\int_0^{x}\int_0^y\left( \frac{1}{2}u + \frac{3}{2}v\right)dvdu
  $$
\end{enumerate}

# Estadística y probabilidad

1. ¿Qué mide la correlación?
2. Menciona dos medidas de tendencia central.
3. Menciona dos medidas de dispersión.
4. ¿Qué es una variable aleatoria?
5. ¿Cuál es la diferencia entre funciones de densidad de probabilidad y funciones de masa de probabilidad?
6. Respecto a la anterior pregunta, ¿con qué tipo de función (de masa o densidad) usarías cuál ecuación para obtener el valor esperado?

\begin{enumerate}
  \setlength{\itemsep}{0pt}
  \setlength{\parskip}{0pt}
  \setlength{\parsep}{0pt}
  \item ¿De masa o de densidad?
  $$
    \mathbf{E}[x] = \sum_{i=1}^n x_ip_i
  $$
  \item ¿De masa o de densidad?
  $$
    \mathbf{E}[x] = \int xf(x)\text{d}x
  $$
\end{enumerate}